/**
 * Olamee Design System — Icon Registry (FontAwesome Pro 6.5.1)
 *
 * Maps icon names to FontAwesome class strings.
 * Every icon renders as an <i> element with FA classes.
 * Sizing is handled by the Icon wrapper component via font-size.
 *
 * Style prefixes (Olamee design system uses regular as default):
 *   fa-regular (far)  — outlined, weight 400 (DEFAULT)
 *   fa-light (fal)    — light, weight 300 (selective use)
 *   fa-regular (fas)    — filled, weight 900 (emphasis only)
 *   fa-thin (fat)     — hairline, weight 100 (rare)
 *   fa-brands (fab)   — brand logos
 *
 * Usage:
 *   <Icon name="heart" />         → <i class="fa-regular fa-heart" />
 *   <Icon name="star" />          → <i class="fa-regular fa-star" />
 *   <Icon faClass="fa-light fa-bell" />  → custom FA class
 */

export type IconCategory = 'general' | 'payment' | 'olamee' | 'social';

export interface IconEntry {
  /** FontAwesome class string, e.g. "fa-regular fa-heart" */
  faClass: string;
  category: IconCategory;
}

// ── General Icons ───────────────────────────────────────────────

// ── Payment Icons ───────────────────────────────────────────────

// ── Olamee Custom Icons (using closest FA equivalents) ──────────

// ── Social Icons ────────────────────────────────────────────────

// ── Registry ────────────────────────────────────────────────────

export const iconRegistry = {
  // General
  heart:            { faClass: 'fa-regular fa-heart', category: 'general' as const },
  star:             { faClass: 'fa-regular fa-star', category: 'general' as const },
  bell:             { faClass: 'fa-regular fa-bell', category: 'general' as const },
  search:           { faClass: 'fa-regular fa-magnifying-glass', category: 'general' as const },
  user:             { faClass: 'fa-regular fa-user', category: 'general' as const },
  globe:            { faClass: 'fa-regular fa-globe', category: 'general' as const },
  trash:            { faClass: 'fa-regular fa-trash', category: 'general' as const },
  'chevron-down':   { faClass: 'fa-regular fa-chevron-down', category: 'general' as const },
  'chevron-right':  { faClass: 'fa-regular fa-chevron-right', category: 'general' as const },
  'chevron-left':   { faClass: 'fa-regular fa-chevron-left', category: 'general' as const },
  'chevron-up':     { faClass: 'fa-regular fa-chevron-up', category: 'general' as const },
  'arrow-right':    { faClass: 'fa-regular fa-arrow-right', category: 'general' as const },
  'arrow-left':     { faClass: 'fa-regular fa-arrow-left', category: 'general' as const },
  'arrow-up':       { faClass: 'fa-regular fa-arrow-up', category: 'general' as const },
  'arrow-down':     { faClass: 'fa-regular fa-arrow-down', category: 'general' as const },
  plus:             { faClass: 'fa-regular fa-plus', category: 'general' as const },
  minus:            { faClass: 'fa-regular fa-minus', category: 'general' as const },
  check:            { faClass: 'fa-regular fa-check', category: 'general' as const },
  x:                { faClass: 'fa-regular fa-xmark', category: 'general' as const },
  eye:              { faClass: 'fa-regular fa-eye', category: 'general' as const },
  'eye-off':        { faClass: 'fa-regular fa-eye-slash', category: 'general' as const },
  calendar:         { faClass: 'fa-regular fa-calendar', category: 'general' as const },
  lock:             { faClass: 'fa-regular fa-lock', category: 'general' as const },
  home:             { faClass: 'fa-regular fa-house', category: 'general' as const },
  bookmark:         { faClass: 'fa-regular fa-bookmark', category: 'general' as const },
  settings:         { faClass: 'fa-regular fa-gear', category: 'general' as const },
  copy:             { faClass: 'fa-regular fa-copy', category: 'general' as const },
  filter:           { faClass: 'fa-regular fa-filter', category: 'general' as const },
  sparkle:          { faClass: 'fa-regular fa-sparkles', category: 'general' as const },
  link:             { faClass: 'fa-regular fa-link', category: 'general' as const },
  clock:            { faClass: 'fa-regular fa-clock', category: 'general' as const },
  upload:           { faClass: 'fa-regular fa-cloud-arrow-up', category: 'general' as const },
  file:             { faClass: 'fa-regular fa-file', category: 'general' as const },
  'circle-xmark':   { faClass: 'fa-regular fa-circle-xmark', category: 'general' as const },
  'ellipsis-vertical': { faClass: 'fa-regular fa-ellipsis-vertical', category: 'general' as const },

  // Additional general icons from Figma
  'circle-minus':   { faClass: 'fa-regular fa-circle-minus', category: 'general' as const },
  'circle-plus':    { faClass: 'fa-regular fa-circle-plus', category: 'general' as const },
  flag:             { faClass: 'fa-regular fa-flag', category: 'general' as const },
  'clapperboard-play': { faClass: 'fa-regular fa-clapperboard', category: 'general' as const },
  'notes-sticky':   { faClass: 'fa-regular fa-note-sticky', category: 'general' as const },
  'share-nodes':    { faClass: 'fa-regular fa-share-nodes', category: 'general' as const },
  asterisk:         { faClass: 'fa-regular fa-asterisk', category: 'general' as const },
  'head-side-headphones': { faClass: 'fa-regular fa-headphones', category: 'general' as const },
  'user-tie-hair':  { faClass: 'fa-regular fa-user', category: 'general' as const },
  'chart-mixed':    { faClass: 'fa-regular fa-chart-mixed', category: 'general' as const },
  'calculator-simple': { faClass: 'fa-regular fa-calculator', category: 'general' as const },
  'user-xmark':     { faClass: 'fa-regular fa-user-xmark', category: 'general' as const },
  'umbrella-beach': { faClass: 'fa-regular fa-umbrella-beach', category: 'general' as const },
  brightness:       { faClass: 'fa-regular fa-sun', category: 'general' as const },
  'badge-check':    { faClass: 'fa-regular fa-badge-check', category: 'general' as const },
  'users-grp':      { faClass: 'fa-regular fa-users', category: 'general' as const },
  ellipsis:         { faClass: 'fa-regular fa-ellipsis', category: 'general' as const },
  'arrow-left-right': { faClass: 'fa-regular fa-arrow-left-right', category: 'general' as const },
  'arrow-down-left-and-arrow-up-right-to-center': { faClass: 'fa-regular fa-arrow-down-left-and-arrow-up-right-to-center', category: 'general' as const },
  'hexagon-image':  { faClass: 'fa-regular fa-image', category: 'general' as const },
  'arrow-right-arrow-left': { faClass: 'fa-regular fa-arrow-right-arrow-left', category: 'general' as const },
  'list-view':      { faClass: 'fa-regular fa-list', category: 'general' as const },
  'grip-lines':     { faClass: 'fa-regular fa-grip-lines', category: 'general' as const },
  'circle-info':    { faClass: 'fa-regular fa-circle-info', category: 'general' as const },
  'people-line':    { faClass: 'fa-regular fa-people-line', category: 'general' as const },
  sidebar:          { faClass: 'fa-regular fa-sidebar', category: 'general' as const },
  'square-p':       { faClass: 'fa-regular fa-square-p', category: 'general' as const },
  'slider-new':     { faClass: 'fa-regular fa-sliders', category: 'general' as const },
  'calendar-week':  { faClass: 'fa-regular fa-calendar-week', category: 'general' as const },
  'triangle-exclamation': { faClass: 'fa-regular fa-triangle-exclamation', category: 'general' as const },
  loader:           { faClass: 'fa-regular fa-spinner', category: 'general' as const },
  thumbstack:       { faClass: 'fa-regular fa-thumbtack', category: 'general' as const },
  'delete-left':    { faClass: 'fa-regular fa-delete-left', category: 'general' as const },
  'circle-small':   { faClass: 'fa-regular fa-circle', category: 'general' as const },
  unlock:           { faClass: 'fa-regular fa-unlock', category: 'general' as const },
  gears:            { faClass: 'fa-regular fa-gears', category: 'general' as const },
  table:            { faClass: 'fa-regular fa-table', category: 'general' as const },
  'badge-percentage': { faClass: 'fa-regular fa-percent', category: 'general' as const },
  mobile:           { faClass: 'fa-regular fa-mobile', category: 'general' as const },
  'comment-lines':  { faClass: 'fa-regular fa-comment-lines', category: 'general' as const },
  camera:           { faClass: 'fa-regular fa-camera', category: 'general' as const },
  bars:             { faClass: 'fa-regular fa-bars', category: 'general' as const },
  'arrow-up-from-bracket': { faClass: 'fa-regular fa-arrow-up-from-bracket', category: 'general' as const },
  pen:              { faClass: 'fa-regular fa-pen', category: 'general' as const },
  'circle-1':       { faClass: 'fa-regular fa-circle-1', category: 'general' as const },
  'circle-2':       { faClass: 'fa-regular fa-circle-2', category: 'general' as const },
  'circle-3':       { faClass: 'fa-regular fa-circle-3', category: 'general' as const },
  'circle-4':       { faClass: 'fa-regular fa-circle-4', category: 'general' as const },
  'circle-half-stroke': { faClass: 'fa-regular fa-circle-half-stroke', category: 'general' as const },
  calculator:       { faClass: 'fa-regular fa-calculator', category: 'general' as const },
  medal:            { faClass: 'fa-regular fa-medal', category: 'general' as const },
  'collapse-left':  { faClass: 'fa-regular fa-sidebar', category: 'general' as const },
  'pen-sparkle':    { faClass: 'fa-regular fa-wand-magic-sparkles', category: 'general' as const },
  'bullhorn':       { faClass: 'fa-regular fa-bullhorn', category: 'general' as const },
  'clipboard-check': { faClass: 'fa-regular fa-clipboard-check', category: 'general' as const },
  timer:            { faClass: 'fa-regular fa-timer', category: 'general' as const },
  'collapse-right': { faClass: 'fa-regular fa-sidebar-flip', category: 'general' as const },
  scissors:         { faClass: 'fa-regular fa-scissors', category: 'general' as const },
  'scissors-sparkle': { faClass: 'fa-regular fa-wand-magic-sparkles', category: 'general' as const },
  'circle-video':   { faClass: 'fa-regular fa-circle-play', category: 'general' as const },
  'pause-updated':  { faClass: 'fa-regular fa-pause', category: 'general' as const },
  circle:           { faClass: 'fa-regular fa-circle', category: 'general' as const },
  'circle-dashed':  { faClass: 'fa-regular fa-circle-dashed', category: 'general' as const },
  map:              { faClass: 'fa-regular fa-map', category: 'general' as const },
  'alarm-clock':    { faClass: 'fa-regular fa-alarm-clock', category: 'general' as const },
  'business-time':  { faClass: 'fa-regular fa-business-time', category: 'general' as const },
  'calendar-xmark': { faClass: 'fa-regular fa-calendar-xmark', category: 'general' as const },
  'not-equal':      { faClass: 'fa-regular fa-not-equal', category: 'general' as const },
  'box-archive':    { faClass: 'fa-regular fa-box-archive', category: 'general' as const },
  stars:            { faClass: 'fa-regular fa-stars', category: 'general' as const },
  award:            { faClass: 'fa-regular fa-award', category: 'general' as const },
  'cloud-arrow-down': { faClass: 'fa-regular fa-cloud-arrow-down', category: 'general' as const },
  'arrow-down-to-bracket': { faClass: 'fa-regular fa-arrow-down-to-bracket', category: 'general' as const },
  'location-arrow': { faClass: 'fa-regular fa-location-arrow', category: 'general' as const },
  'message-lines':  { faClass: 'fa-regular fa-message-lines', category: 'general' as const },
  database:         { faClass: 'fa-regular fa-database', category: 'general' as const },
  'user-gear':      { faClass: 'fa-regular fa-user-gear', category: 'general' as const },
  'text-size':      { faClass: 'fa-regular fa-text-size', category: 'general' as const },
  'change-mood-ai': { faClass: 'fa-regular fa-face-smile', category: 'general' as const },
  'phone-slash':    { faClass: 'fa-regular fa-phone-slash', category: 'general' as const },
  'filled-circle':  { faClass: 'fa-solid fa-circle', category: 'general' as const },
  'wand-magic':     { faClass: 'fa-regular fa-wand-magic', category: 'general' as const },
  'bars-filter':    { faClass: 'fa-regular fa-bars-filter', category: 'general' as const },
  'phone-xmark':    { faClass: 'fa-regular fa-phone-slash', category: 'general' as const },
  forward:          { faClass: 'fa-regular fa-forward', category: 'general' as const },
  'user-magnifying-glass': { faClass: 'fa-regular fa-user-magnifying-glass', category: 'general' as const },
  shuffle:          { faClass: 'fa-regular fa-shuffle', category: 'general' as const },
  key:              { faClass: 'fa-regular fa-key', category: 'general' as const },
  'alarm-exclamation': { faClass: 'fa-regular fa-alarm-exclamation', category: 'general' as const },
  'ai-lengthen':    { faClass: 'fa-regular fa-arrow-up-right', category: 'general' as const },
  'ai-shorten':     { faClass: 'fa-regular fa-arrow-down-left', category: 'general' as const },
  'sliders-simple': { faClass: 'fa-regular fa-sliders', category: 'general' as const },
  'angles-right':   { faClass: 'fa-regular fa-angles-right', category: 'general' as const },
  'arrow-down-right': { faClass: 'fa-regular fa-arrow-down-right', category: 'general' as const },
  'arrow-down-arrow-up': { faClass: 'fa-regular fa-arrow-down-arrow-up', category: 'general' as const },
  'plus-small':     { faClass: 'fa-regular fa-plus', category: 'general' as const },
  divide:           { faClass: 'fa-regular fa-divide', category: 'general' as const },
  equals:           { faClass: 'fa-regular fa-equals', category: 'general' as const },
  'arrow-up-arrow-down': { faClass: 'fa-regular fa-arrow-up-arrow-down', category: 'general' as const },
  'arrow-left-long-to-line': { faClass: 'fa-regular fa-arrow-left-long', category: 'general' as const },
  'arrow-right-long-to-line': { faClass: 'fa-regular fa-arrow-right-long', category: 'general' as const },
  'arrow-left-from-line': { faClass: 'fa-regular fa-arrow-left-from-line', category: 'general' as const },
  'arrow-right-from-line': { faClass: 'fa-regular fa-arrow-right-from-line', category: 'general' as const },
  'face-vomit':     { faClass: 'fa-regular fa-face-vomiting', category: 'general' as const },
  'face-angry':     { faClass: 'fa-regular fa-face-angry', category: 'general' as const },
  'face-dissapointed': { faClass: 'fa-regular fa-face-frown', category: 'general' as const },
  'face-smile':     { faClass: 'fa-regular fa-face-smile', category: 'general' as const },
  'face-expressionless': { faClass: 'fa-regular fa-face-expressionless', category: 'general' as const },
  'do-not-enter':   { faClass: 'fa-regular fa-do-not-enter', category: 'general' as const },
  'x-mark-small':   { faClass: 'fa-regular fa-xmark', category: 'general' as const },
  subscript:        { faClass: 'fa-regular fa-subscript', category: 'general' as const },
  'folder-user':    { faClass: 'fa-regular fa-folder-user', category: 'general' as const },
  down:             { faClass: 'fa-regular fa-arrow-down', category: 'general' as const },
  'paperclip-vertical': { faClass: 'fa-regular fa-paperclip', category: 'general' as const },
  'circle-phone-hangup': { faClass: 'fa-regular fa-phone-hangup', category: 'general' as const },
  users:            { faClass: 'fa-regular fa-users', category: 'general' as const },
  columns:          { faClass: 'fa-regular fa-columns', category: 'general' as const },
  'file-arrow-down': { faClass: 'fa-regular fa-file-arrow-down', category: 'general' as const },
  'file-pdf':       { faClass: 'fa-regular fa-file-pdf', category: 'general' as const },
  'ballot-check':   { faClass: 'fa-regular fa-ballot-check', category: 'general' as const },
  'shield-check':   { faClass: 'fa-regular fa-shield-check', category: 'general' as const },
  'user-plus':      { faClass: 'fa-regular fa-user-plus', category: 'general' as const },
  trophy:           { faClass: 'fa-regular fa-trophy', category: 'general' as const },
  suitcase:         { faClass: 'fa-regular fa-suitcase', category: 'general' as const },
  video:            { faClass: 'fa-regular fa-video', category: 'general' as const },
  scroll:           { faClass: 'fa-regular fa-scroll', category: 'general' as const },
  bolt:             { faClass: 'fa-regular fa-bolt', category: 'general' as const },
  'heart-pulse':    { faClass: 'fa-regular fa-heart-pulse', category: 'general' as const },
  books:            { faClass: 'fa-regular fa-books', category: 'general' as const },
  phone:            { faClass: 'fa-regular fa-phone', category: 'general' as const },
  'pen-to-box':     { faClass: 'fa-regular fa-pen-to-square', category: 'general' as const },
  'table-list':     { faClass: 'fa-regular fa-table-list', category: 'general' as const },
  'calendar-edit':  { faClass: 'fa-regular fa-calendar-pen', category: 'general' as const },
  envelope:         { faClass: 'fa-regular fa-envelope', category: 'general' as const },
  'calendar-circle-user': { faClass: 'fa-regular fa-calendar-circle-user', category: 'general' as const },
  volume:           { faClass: 'fa-regular fa-volume-high', category: 'general' as const },
  'volume-slash':   { faClass: 'fa-regular fa-volume-slash', category: 'general' as const },
  'superscript':    { faClass: 'fa-regular fa-superscript', category: 'general' as const },
  rank:             { faClass: 'fa-regular fa-ranking-star', category: 'general' as const },
  'arrows-rotate':  { faClass: 'fa-regular fa-arrows-rotate', category: 'general' as const },
  'comments-question': { faClass: 'fa-regular fa-comments-question', category: 'general' as const },
  'grid-dots':      { faClass: 'fa-regular fa-grip-dots', category: 'general' as const },
  'new-file-x-mark': { faClass: 'fa-regular fa-file-xmark', category: 'general' as const },
  'person-circle-plus': { faClass: 'fa-regular fa-person-circle-plus', category: 'general' as const },
  scale:            { faClass: 'fa-regular fa-scale-balanced', category: 'general' as const },
  'microphone-slash': { faClass: 'fa-regular fa-microphone-slash', category: 'general' as const },
  question:         { faClass: 'fa-regular fa-question', category: 'general' as const },
  'arrow-up-right-from-square': { faClass: 'fa-regular fa-arrow-up-right-from-square', category: 'general' as const },
  'paperclip':      { faClass: 'fa-regular fa-paperclip', category: 'general' as const },
  'phone-volume':   { faClass: 'fa-regular fa-phone-volume', category: 'general' as const },
  input:            { faClass: 'fa-regular fa-input-text', category: 'general' as const },
  'calendar-pen':   { faClass: 'fa-regular fa-calendar-pen', category: 'general' as const },
  'file-user':      { faClass: 'fa-regular fa-file-user', category: 'general' as const },
  'address-book':   { faClass: 'fa-regular fa-address-book', category: 'general' as const },
  'file-pen':       { faClass: 'fa-regular fa-file-pen', category: 'general' as const },
  notes:            { faClass: 'fa-regular fa-note-sticky', category: 'general' as const },
  building:         { faClass: 'fa-regular fa-building', category: 'general' as const },
  expand:           { faClass: 'fa-regular fa-expand', category: 'general' as const },
  'arrows-maximize': { faClass: 'fa-regular fa-expand', category: 'general' as const },
  hourglass:        { faClass: 'fa-regular fa-hourglass-end', category: 'general' as const },
  'paper-plane':    { faClass: 'fa-regular fa-paper-plane', category: 'general' as const },
  'thumbs-up':      { faClass: 'fa-regular fa-thumbs-up', category: 'general' as const },
  'address-card':   { faClass: 'fa-regular fa-address-card', category: 'general' as const },
  'bars-staggered': { faClass: 'fa-regular fa-bars-staggered', category: 'general' as const },
  'arrow-rotate-left': { faClass: 'fa-regular fa-arrow-rotate-left', category: 'general' as const },
  'item-icon':      { faClass: 'fa-regular fa-square', category: 'general' as const },
  'comment-questionmark': { faClass: 'fa-regular fa-comments-question', category: 'general' as const },
  'table-layout':   { faClass: 'fa-regular fa-table-layout', category: 'general' as const },
  'paper-plane-side': { faClass: 'fa-regular fa-paper-plane', category: 'general' as const },
  shield:           { faClass: 'fa-regular fa-shield', category: 'general' as const },
  toolbox:          { faClass: 'fa-regular fa-toolbox', category: 'general' as const },
  'circle-phone':   { faClass: 'fa-regular fa-circle-phone', category: 'general' as const },
  memo:             { faClass: 'fa-regular fa-memo', category: 'general' as const },
  folder:           { faClass: 'fa-regular fa-folder', category: 'general' as const },
  'arrow-up-right-and-arrow-down-left-from-center': { faClass: 'fa-regular fa-arrow-up-right-and-arrow-down-left-from-center', category: 'general' as const },
  'user-invert-circle': { faClass: 'fa-regular fa-user-circle', category: 'general' as const },
  'user-circle':    { faClass: 'fa-regular fa-user-circle', category: 'general' as const },
  resize:           { faClass: 'fa-regular fa-expand', category: 'general' as const },
  'circle-play':    { faClass: 'fa-regular fa-circle-play', category: 'general' as const },
  ban:              { faClass: 'fa-regular fa-ban', category: 'general' as const },
  reverse:          { faClass: 'fa-regular fa-arrow-left-arrow-right', category: 'general' as const },
  radio:            { faClass: 'fa-regular fa-circle', category: 'general' as const },
  triangle:         { faClass: 'fa-regular fa-triangle', category: 'general' as const },
  'file-arrow-up-2': { faClass: 'fa-regular fa-file-arrow-up', category: 'general' as const },
  glasses:          { faClass: 'fa-regular fa-glasses', category: 'general' as const },
  screen:           { faClass: 'fa-regular fa-display', category: 'general' as const },
  replay:           { faClass: 'fa-regular fa-arrow-rotate-right', category: 'general' as const },
  'image-map':      { faClass: 'fa-regular fa-image', category: 'general' as const },
  'brackets-curly': { faClass: 'fa-regular fa-brackets-curly', category: 'general' as const },
  'calendar-clock': { faClass: 'fa-regular fa-calendar-clock', category: 'general' as const },
  buildings:        { faClass: 'fa-regular fa-buildings', category: 'general' as const },
  checkbox:         { faClass: 'fa-regular fa-square-check', category: 'general' as const },
  brain:            { faClass: 'fa-regular fa-brain', category: 'general' as const },
  download:         { faClass: 'fa-regular fa-download', category: 'general' as const },
  'message-exclamation': { faClass: 'fa-regular fa-message-exclamation', category: 'general' as const },
  clone:            { faClass: 'fa-regular fa-clone', category: 'general' as const },
  groups:           { faClass: 'fa-regular fa-people-group', category: 'general' as const },
  'link-simple':    { faClass: 'fa-regular fa-link-simple', category: 'general' as const },
  'message-question': { faClass: 'fa-regular fa-message-question', category: 'general' as const },
  'arrow-progress': { faClass: 'fa-regular fa-arrow-up-right', category: 'general' as const },
  'user-clock':     { faClass: 'fa-regular fa-user-clock', category: 'general' as const },
  microphone:       { faClass: 'fa-regular fa-microphone', category: 'general' as const },
  clipboard:        { faClass: 'fa-regular fa-clipboard', category: 'general' as const },
  hand:             { faClass: 'fa-regular fa-hand', category: 'general' as const },
  'plus-minus':     { faClass: 'fa-regular fa-plus-minus', category: 'general' as const },
  'door-open':      { faClass: 'fa-regular fa-door-open', category: 'general' as const },
  'flip-horizontal': { faClass: 'fa-regular fa-arrow-left-right', category: 'general' as const },
  'calendar-circle-plus': { faClass: 'fa-regular fa-calendar-circle-plus', category: 'general' as const },
  'filter-settings-new': { faClass: 'fa-regular fa-sliders', category: 'general' as const },
  note:             { faClass: 'fa-regular fa-note-sticky', category: 'general' as const },
  'code-branch':    { faClass: 'fa-regular fa-code-branch', category: 'general' as const },
  'file-arrow-up':  { faClass: 'fa-regular fa-file-arrow-up', category: 'general' as const },
  headset:          { faClass: 'fa-regular fa-headset', category: 'general' as const },
  'mobile-notch':   { faClass: 'fa-regular fa-mobile', category: 'general' as const },
  'users-viewfinder': { faClass: 'fa-regular fa-people-group', category: 'general' as const },
  'calendar-lines': { faClass: 'fa-regular fa-calendar-lines', category: 'general' as const },
  'lock-a':         { faClass: 'fa-regular fa-lock', category: 'general' as const },
  'circle-up':      { faClass: 'fa-regular fa-circle-up', category: 'general' as const },
  'circle-down':    { faClass: 'fa-regular fa-circle-down', category: 'general' as const },
  'user-group':     { faClass: 'fa-regular fa-user-group', category: 'general' as const },
  wrench:           { faClass: 'fa-regular fa-wrench', category: 'general' as const },
  stop:             { faClass: 'fa-regular fa-stop', category: 'general' as const },
  empty:            { faClass: 'fa-regular fa-square', category: 'general' as const },
  progress:         { faClass: 'fa-regular fa-hourglass-half', category: 'general' as const },
  'globe-2':        { faClass: 'fa-regular fa-globe', category: 'general' as const },
  'announcement-01': { faClass: 'fa-regular fa-megaphone', category: 'general' as const },
  'calendar-deadline': { faClass: 'fa-regular fa-calendar', category: 'general' as const },
  decimal:          { faClass: 'fa-regular fa-percent', category: 'general' as const },
  'cards-blank':    { faClass: 'fa-regular fa-square', category: 'general' as const },
  'no-overtime':    { faClass: 'fa-regular fa-hourglass-end', category: 'general' as const },
  'pointing-arrow': { faClass: 'fa-regular fa-arrow-pointer', category: 'general' as const },
  duplicate:        { faClass: 'fa-regular fa-copy', category: 'general' as const },
  'layout-grid':    { faClass: 'fa-regular fa-table', category: 'general' as const },
  resume:           { faClass: 'fa-regular fa-file-lines', category: 'general' as const },
  paypal:           { faClass: 'fa-brands fa-paypal', category: 'payment' as const },
  letter:           { faClass: 'fa-regular fa-envelope', category: 'general' as const },
  'shield-filled':  { faClass: 'fa-solid fa-shield', category: 'general' as const },
  'shield-half-filled': { faClass: 'fa-regular fa-shield', category: 'general' as const },
  group:            { faClass: 'fa-regular fa-people-group', category: 'general' as const },
  'square-dashed':  { faClass: 'fa-regular fa-square-dashed', category: 'general' as const },
  'grid-2':         { faClass: 'fa-regular fa-grip-dots', category: 'general' as const },
  'circle-question': { faClass: 'fa-regular fa-circle-question', category: 'general' as const },
  'circle-check':   { faClass: 'fa-regular fa-circle-check', category: 'general' as const },
  'circle-arrow-up': { faClass: 'fa-regular fa-circle-arrow-up', category: 'general' as const },
  'circle-arrow-down': { faClass: 'fa-regular fa-circle-arrow-down', category: 'general' as const },
  'circle-exclamation': { faClass: 'fa-regular fa-circle-exclamation', category: 'general' as const },
  eyedropper:       { faClass: 'fa-regular fa-eyedropper', category: 'general' as const },
  'full-screen':    { faClass: 'fa-regular fa-maximize', category: 'general' as const },
  'link-slash':     { faClass: 'fa-regular fa-link-slash', category: 'general' as const },
  'arrow-right-from-bracket': { faClass: 'fa-regular fa-arrow-right-from-bracket', category: 'general' as const },
  'location-crosshairs': { faClass: 'fa-regular fa-location-crosshairs', category: 'general' as const },
  'clapperboard':   { faClass: 'fa-regular fa-clapperboard', category: 'general' as const },
  'angles-left':    { faClass: 'fa-regular fa-angles-left', category: 'general' as const },
  'arrow-turn-down-left': { faClass: 'fa-regular fa-arrow-turn-down-left', category: 'general' as const },
  'arrow-turn-down-right': { faClass: 'fa-regular fa-arrow-turn-down-right', category: 'general' as const },
  'arrow-turn-left': { faClass: 'fa-regular fa-arrow-turn-left', category: 'general' as const },
  'arrow-turn-right': { faClass: 'fa-regular fa-arrow-turn-right', category: 'general' as const },
  'user-check':     { faClass: 'fa-regular fa-user-check', category: 'general' as const },
  'rotate-clock-left': { faClass: 'fa-regular fa-arrow-rotate-left', category: 'general' as const },
  'magnifying-glass-plus': { faClass: 'fa-regular fa-magnifying-glass-plus', category: 'general' as const },
  'magnifying-glass-chart': { faClass: 'fa-regular fa-magnifying-glass-chart', category: 'general' as const },
  'layer-group':    { faClass: 'fa-regular fa-layer-group', category: 'general' as const },
  'less-than':      { faClass: 'fa-regular fa-less-than', category: 'general' as const },
  'greater-than':   { faClass: 'fa-regular fa-greater-than', category: 'general' as const },
  'less-than-equal': { faClass: 'fa-regular fa-less-than-equal', category: 'general' as const },
  'greater-than-equal': { faClass: 'fa-regular fa-greater-than-equal', category: 'general' as const },
  'hexagon-check':  { faClass: 'fa-regular fa-check-circle', category: 'general' as const },
  'focal-point':    { faClass: 'fa-regular fa-circle', category: 'general' as const },

  // Payment
  'credit-card':      { faClass: 'fa-regular fa-credit-card', category: 'payment' as const },
  'money-bill':       { faClass: 'fa-regular fa-money-bill', category: 'payment' as const },
  'building-columns': { faClass: 'fa-regular fa-building-columns', category: 'payment' as const },
  briefcase:          { faClass: 'fa-regular fa-briefcase', category: 'payment' as const },
  'chart-simple':     { faClass: 'fa-regular fa-chart-simple', category: 'payment' as const },
  'graduation-cap':   { faClass: 'fa-regular fa-graduation-cap', category: 'payment' as const },
  mug:                { faClass: 'fa-regular fa-mug-hot', category: 'payment' as const },
  'id-card':          { faClass: 'fa-regular fa-id-card', category: 'payment' as const },
  receipt:            { faClass: 'fa-regular fa-receipt', category: 'payment' as const },

  // Olamee (Figma custom icons - mapped to closest FA equivalents)
  'om-dashboard':   { faClass: 'fa-regular fa-grid-2', category: 'olamee' as const },
  'om-applicants':  { faClass: 'fa-regular fa-users', category: 'olamee' as const },
  'om-assessments': { faClass: 'fa-regular fa-clipboard-check', category: 'olamee' as const },
  'om-settings':    { faClass: 'fa-regular fa-gear', category: 'olamee' as const },
  'om-attendance':  { faClass: 'fa-regular fa-calendar-check', category: 'olamee' as const },
  'om-clients':     { faClass: 'fa-regular fa-user-group', category: 'olamee' as const },
  'om-manage-clients': { faClass: 'fa-regular fa-users', category: 'olamee' as const },
  'om-team-members': { faClass: 'fa-regular fa-people-group', category: 'olamee' as const },
  'om-timeoff':     { faClass: 'fa-regular fa-calendar-xmark', category: 'olamee' as const },
  'om-support':     { faClass: 'fa-regular fa-headset', category: 'olamee' as const },
  'om-manage-payments': { faClass: 'fa-regular fa-credit-card', category: 'olamee' as const },
  'om-team':        { faClass: 'fa-regular fa-people-group', category: 'olamee' as const },
  'om-member-activities': { faClass: 'fa-regular fa-clock', category: 'olamee' as const },
  'om-collapse':    { faClass: 'fa-regular fa-chevron-left', category: 'olamee' as const },
  'om-workflows':   { faClass: 'fa-regular fa-diagram-project', category: 'olamee' as const },
  'om-payment-history': { faClass: 'fa-regular fa-history', category: 'olamee' as const },
  'om-add-new-team-member': { faClass: 'fa-regular fa-user-plus', category: 'olamee' as const },
  'om-payments-reports': { faClass: 'fa-regular fa-chart-line', category: 'olamee' as const },
  'om-expand':      { faClass: 'fa-regular fa-chevron-right', category: 'olamee' as const },
  'om-applicant-list': { faClass: 'fa-regular fa-list', category: 'olamee' as const },
  'om-payrolls':    { faClass: 'fa-regular fa-file-invoice', category: 'olamee' as const },
  'om-interviews':  { faClass: 'fa-regular fa-microphone', category: 'olamee' as const },
  'om-eor-cost-calculator': { faClass: 'fa-regular fa-calculator', category: 'olamee' as const },
  'om-position-request': { faClass: 'fa-regular fa-clipboard', category: 'olamee' as const },
  'om-jobs':        { faClass: 'fa-regular fa-briefcase', category: 'olamee' as const },
  'om-generate-invoice': { faClass: 'fa-regular fa-file-invoice', category: 'olamee' as const },
  'om-projects':    { faClass: 'fa-regular fa-diagram-project', category: 'olamee' as const },
  'om-payments':    { faClass: 'fa-regular fa-credit-card', category: 'olamee' as const },
  'om-interview-calendars': { faClass: 'fa-regular fa-calendar', category: 'olamee' as const },
  'om-submit-feedback': { faClass: 'fa-regular fa-comment-dots', category: 'olamee' as const },
  'om-talent-pool': { faClass: 'fa-regular fa-users', category: 'olamee' as const },
  'om-jobs-listing': { faClass: 'fa-regular fa-list', category: 'olamee' as const },
  'om-reports':     { faClass: 'fa-regular fa-file-lines', category: 'olamee' as const },

  // Social
  'x-twitter':  { faClass: 'fa-brands fa-x-twitter', category: 'social' as const },
  linkedin:     { faClass: 'fa-brands fa-linkedin', category: 'social' as const },
  facebook:     { faClass: 'fa-brands fa-facebook', category: 'social' as const },
  instagram:    { faClass: 'fa-brands fa-instagram', category: 'social' as const },
  gmail:        { faClass: 'fa-regular fa-envelope', category: 'social' as const },
} satisfies Record<string, IconEntry>;

export type IconName = keyof typeof iconRegistry;

export function getIconsByCategory(category: IconCategory): [string, IconEntry][] {
  return Object.entries(iconRegistry).filter(([, entry]) => entry.category === category);
}

export const iconCategories: { key: IconCategory; label: string }[] = [
  { key: 'general', label: 'General' },
  { key: 'payment', label: 'Payment' },
  { key: 'olamee', label: 'Custom / Olamee' },
  { key: 'social', label: 'Social' },
];
